[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -std=gnu++17

lib_deps =
    blynkkk/Blynk
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
